### ISSUE TITLE
Not working with OTel v0.18.0

### ISSUE THREAD

**Issue by prmsrswt** [newrelic/opentelemetry-exporter-go#72]
In opentelemetr-go v0.18.0, the package `label` was renamed to `attribute` (See https://github.com/open-telemetry/opentelemetry-go/pull/1541). `newrelic/internal/transform/metric.go` still imports the label package, due to which the installation is failing.

Running `go get -u github.com/newrelic/opentelemetry-exporter-go/newrelic` gives me:

```
go: downloading go.opentelemetry.io/otel/sdk/export/metric v0.18.0
go: downloading go.opentelemetry.io/otel/sdk/metric v0.18.0
github.com/newrelic/opentelemetry-exporter-go/newrelic imports
	github.com/newrelic/opentelemetry-exporter-go/newrelic/internal/transform imports
	go.opentelemetry.io/otel/label: cannot find module providing package go.opentelemetry.io/otel/label
```

**Comment by RichVanderwal** [comment]
Hi @prmsrswt , thanks for writing in! PR #71, submitted by @akulnurislam, upgrades the OpenTelemetry Exporter for Go to use v0.18.0 of the OpenTelemetry-Go API.

Stay tuned to see this PR get merged into a new release of the OpenTelemetry Exporter for Go.

**Comment by prmsrswt** [comment]
Whoops, sorry. I missed the PR. Thanks for your patience.
